version: '3'
services:
  # Define dB container
  nosql-db:
    image: mongo:4.4
    container_name: nosql-db
    ports:
      - "27017:27017"

  # Define Flask app container
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "8080:8080"
    depends_on:
      - nosql-db
    environment:
      DATABASE_HOST: nosql-db
      DATABASE_PORT: 27017
    restart: always
